name: parcelpoint_operations_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # cupertino_icons: ^0.1.3
  barcode_scan: ^3.0.1
  flutter_svg: ^0.18.0
  # dartx: ^0.4.2
# dependency_overrides:
#   xml: '^4.1.0'

dev_dependencies:
  flutter_test:
    sdk: flutter

# uncomment it to generate icons but keep it commented to run the app. It's not compatible with flutter_svg
# if the build fails, run flutter clean && flutter pub get
#   flutter_launcher_icons: ^0.7.5

# flutter_icons:
#   android: true
#   ios: true
#   image_path: 'assets_dev/images/parcelpoint-stamp.png'
#   adaptive_icon_background: '#000'
#   adaptive_icon_foreground: 'assets_dev/images/parcelpoint-stamp.png'

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/icon-parcel.svg
    - assets/images/icon-barcode.svg
    - assets/images/local-delivery-logo.svg
    - assets/images/icon-qr-barcode.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Scandia
      fonts:
        - asset: assets/fonts/Scandia-Regular.ttf
        - asset: assets/fonts/Scandia-Bold.ttf
          weight: 500
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
